"""enable cascade deletion for docs, messages and chunks

Revision ID: 202824120e18
Revises: 20e7dcdd781d
Create Date: 2026-07-24 13:27:51.626429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202824120e18'
down_revision: Union[str, Sequence[str], None] = '20e7dcdd781d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunks_doc_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'docs', ['doc_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('docs_chat_id_fkey'), 'docs', type_='foreignkey')
    op.create_foreign_key(None, 'docs', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'docs', type_='foreignkey')
    op.create_foreign_key(op.f('docs_chat_id_fkey'), 'docs', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_doc_id_fkey'), 'chunks', 'docs', ['doc_id'], ['id'])
    # ### end Alembic commands ###
