"""Allow repeated doc titles

Revision ID: 20e7dcdd781d
Revises: 117517c56144
Create Date: 2026-07-09 12:08:52.033943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e7dcdd781d'
down_revision: Union[str, Sequence[str], None] = '117517c56144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('docs_title_key'), 'docs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('docs_title_key'), 'docs', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
